[tool.poetry]
name = "sirziamart"
version = "0.1.0"
description = ""
authors = ["Ali-Ahmed999 <150151136+Ali-Ahmed999@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
